package com.inventra.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AiQueryResponse {

    @Schema(description = "Original question asked by the user", example = "Show me all products with low stock")
    private String question;

    @Schema(description = "Classified intent of the question", example = "LOW_STOCK_QUERY")
    private String intent;

    @Schema(description = "Human-readable summary answer generated by Gemini")
    private String summary;

    @Schema(description = "Structured response data (varies by intent)")
    private Object data;
}
