[variables]
SPRING_PROFILES_ACTIVE = "railway"

[phases.setup]
nixPkgs = ["nodejs_20", "jdk21"]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "java $JAVA_OPTS -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xss512k -jar target/inventra-1.0.0.jar --spring.profiles.active=railway"
